lib.lwiki.php: &pre(!lang), &code(!lang) 対応と agh-prog-lang からの移行。&pre(title=) の処理方法の変更。
lwiki (page-convert): コマンドラインからページの再変換を実行するためのコマンド。
lib.lwiki.php (&pre(title=)): bugfix, <pre> 内部に題名を追加していると着色の対象になってしまう。
lib.lwiki.php (&pre(!lang), &code(!lang)): 言語着色を lwiki の枠組み内で指定できるように拡張。言語名を lwiki.php 変換時に決定。
lwiki.js: pre/code class=lwiki-language-lang (上記の言語着色の指定) による着色。
lwiki.css: pre class=lwiki-implicit-title/lwiki-explicit-title (上記言語名の指定) による言語名の表示と体裁。

diff --git a/lwiki b/lwiki
--- a/lwiki
+++ b/lwiki
@@ -168,6 +168,41 @@ function command.archive {
   )
 }
 
+function command.page-convert {
+  if [[ ! -d .lwiki ]]; then
+    echo "lwiki.page-convert: this is not a lwiki directory" >&2
+    return 1
+  fi
+
+  local pageid
+  local fError=
+  local -a pageids
+  pageids=()
+  if (($#)); then
+    for pageid in "$@"; do
+      if [[ ! -f .lwiki/data/page.$pageid.wiki ]]; then
+        echo "lwiki.page-convert: the specified page, pageid=$pageid, is not found." >&2
+        fError=1
+        continue
+      fi
+      pageids+=("$pageid")
+    done
+  else
+    local page
+    for page in .lwiki/data/page.*.wiki; do
+      pageid="${page#.lwiki/data/page.}"
+      pageid="${pageid%.wiki}"
+      pageids+=("$pageid")
+    done
+  fi
+
+  [[ $fError ]] && return 1
+
+  for pageid in "${pageids[@]}"; do
+    echo "$pageid"
+    php "$LWIKIPATH"/lwiki-page-convert.php "$pageid"
+  done
+}
 
 if [[ ! $1 ]]; then
   echo "lwiki: operation not specified" >&2
